---
env:
  matrix:
    - GEOS_VERSION=3.4.2
    - GEOS_VERSION=3.3.8
    - GEOS_VERSION=3.2.3
before_install:
  - rm .travis.yml
  - sudo apt-get update
  - sudo apt-get install -qq sendfile build-essential flex autoconf libtool gfortran xsltproc libproj-dev dblatex
  - git config --global user.name "Build package TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
language: c
script:
  - export LSB_INFO=$( lsb_release -rs )_$( lsb_release -ms )
  - wget -q http://download.osgeo.org/geos/geos-$GEOS_VERSION.tar.bz2
  - tar xvjf geos-$GEOS_VERSION.tar.bz2
  - ( cd geos-$GEOS_VERSION && ./configure --prefix=/home/travis/geos-$GEOS_VERSION && make && make install )
  - tar cvzf geos-$GEOS_VERSION.travis.$LSB_INFO.tar.gz /home/travis/geos-$GEOS_VERSION
  - sendfile geos-$GEOS_VERSION.travis.$LSB_INFO.tar.gz lr@pcorp.us
